# Fixes warning `Your project does not explicitly specify the CocoaPods master specs repo`.
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
use_frameworks!

target 'Example' do
  pod 'LightweightObservable', :path => '../', :testspecs => ['Tests']

  # Development pods.
  pod 'SwiftFormat/CLI', '~> 0.41'
  pod 'SwiftLint', '~> 0.42'
  pod 'SwiftConfigurationFiles', :git => 'https://github.com/fxm90/SwiftConfigurationFiles.git'

  post_install do |installer|

    #
    # Fix warning from `pod install` in Xcode.
    #
    # > The iOS Simulator deployment targets is set to 8.0,
    # > but the range of supported deployment target version for this platform is X.X to Y.Y
    #
    # Source: https://stackoverflow.com/a/63489366
    #
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end
