#
# travis.yml
# Created by Felix Mau (https://felix.hamburg)
#

osx_image: xcode11
language: swift
before_script:
  - cd Example/
  - bundle install
script:
  - bundle exec fastlane format
  - bundle exec fastlane lint
  - bundle exec fastlane tests
  - bundle exec fastlane pod_lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
